# Generated by Django 6.0 on 2025-12-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('conteudo', models.CharField(max_length=70)),
                ('imagem', models.ImageField(upload_to='servicos')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'servico',
                'verbose_name_plural': 'servicos',
            },
        ),
    ]
