# Generated by Django 6.0 on 2026-01-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Unidade')),
                ('tipo', models.CharField(choices=[('matriz', 'Matriz'), ('filial', 'Filial')], default='filial', max_length=10)),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(default='SP', max_length=2, verbose_name='Estado (UF)')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail de Contato')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('mapa_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL do Google Maps')),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição no site')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
